name: 'Validate project'
description: 'Validate project by running linting, static type checking and tests'

runs:
  using: 'composite'
  steps:
    - name: Setup Python
      uses: quintenroets/package-dev-tools/actions/setup-python@main

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]

    - name: Check pre-commit
      uses: pre-commit/action@v3.0.0
