[project]
name = "dev-tools"
version = "0.0.0"
description = "Python package"
authors = [{name = "Quinten Roets", email = "qdr2104@columbia.edu"}]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pygithub>=2.1",
    "python-slugify>=8.0",
    "superpathlib>=1.3",
    "typer>=0.9",
    "quinten-cli>=1.1",
]

[project.optional-dependencies]
dev = [
    "build",
    "bump2version",
    "coverage",
    "hypothesis",
    "pre-commit",
    "pytest",
    "pytest-mypy-plugins",
    "package-dev-tools"
]

[project.urls]
"Source Code" = "https://github.com/quintenroets/dev-tools"

[project.scripts]
substitute_template_name = "dev_tools.cli.substitute_template_name:entry_point"
cleanup_readme = "dev_tools.cli.cleanup_readme:entry_point"
trigger_template_sync = "dev_tools.cli.cleanup_readme:entry_point"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.package-data]
dev_tools = ["py.typed"]

[tool.setuptools]
script-files = ["bin/cleanup_workflows"]

[tool.ruff]
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "UP",  # pyupgrade
]
fix = true

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]

[tool.mypy]
strict = true
no_implicit_reexport = false
