# Some workflows in the template repository do not need to run in derived repositories.
# This action removes them from newly instantiated projects derived from the template repository.

name: 'Cleanup workflows'
description: 'Cleanup workflows'

runs:
  using: 'composite'
  steps:
  - name: Install dependencies
    run: pip install dev-tools
    shell: bash

  - name: Cleanup workflows
    run: cleanup-workflows
    shell: bash
    working-directory: .github
