name: Instantiate new project
description: 'Instantiate new project from template repository'

runs:
  using: 'composite'
  steps:
  - name: Checkout source
    uses: actions/checkout@v3

  - name: Configure git
    run: |
      git config --global user.email "quinten.roets@gmail.com"
      git config --global user.name "Quinten"
    shell: bash

  - name: Substitute template name
    uses: quintenroets/dev-tools/actions/instantiate-new-project/substitute-names@main

  - name: Commit to git
    run: |
      git add .
      git commit -m "Substitute template name"
    shell: bash

  - name: Remove template-only workflows
    uses: quintenroets/dev-tools/actions/instantiate-new-project/cleanup-workflows@main

  - name: Commit to git
    run: |
      git add .
      git commit -m "Remove template-only workflows"
    shell: bash

  - name: Remove template-only documentation
    uses: quintenroets/dev-tools/actions/instantiate-new-project/cleanup-readme@main

  - name: Commit to git
    run: |
      git add .
      git commit -m "Remove template-only documentation"
    shell: bash

  - name: Push changes
    run: |
      git push
    shell: bash
