name: 'Setup Python'
description: 'Setup Python with the minimal supported version as specified in pyproject.toml'

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Extract Python version
      id: extract-python-version
      shell: bash
      run: |
        python_version=$(cat pyproject.toml | grep 'requires-python = ">=' | sed 's/requires-python = ">=//' | sed 's/"//')
        echo "PYTHON_VERSION=$python_version" >> "$GITHUB_OUTPUT"

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ steps.extract-python-version.outputs.PYTHON_VERSION }}
