name: 'Setup environment'
description: 'Setup environment'

inputs:
  python-version:
    description: "Python version to use"
  environment:
    description: "Dependency environment to install"
  editable:
    description: "Install package in editable mode"
  repository:
    description: "Repository to setup"
    default: ${{ github.repository }}
  dependency:
    description: "Dependency to install"

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      if: ${{ inputs.dependency == '' }}
      uses: actions/checkout@v4
      with:
        clean: false
        show-progress: false
        repository: ${{ inputs.repository }}

    - name: Determine Python version
      id: determine-python-version
      shell: bash
      run: |
        if [[ -z "${{ inputs.python-version }}" ]]; then
          python_version=$(cat pyproject.toml | grep 'requires-python = ">=' | sed 's/requires-python = ">=//' | sed 's/"//')
        elif [[ -z "${{ inputs.dependency }}" ]]; then
          python_version=${{ inputs.python-version }}
        else
          python_version=""
        fi
        echo "python_version=$python_version" >> "$GITHUB_OUTPUT"

    - name: Set up Python
      id: setup-python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ steps.determine-python-version.outputs.python_version }}
        cache: pip

    - name: Cache virtual environment
      id: cache
      uses: actions/cache@v4
      env:
        KEY:
          venv
          ${{ inputs.environment }}
          ${{ runner.os }}
          ${{ steps.determine-python-version.outputs.python_version }}
      with:
        path: .venv
        key: ${{ env.KEY }}-${{ hashFiles('pyproject.toml') }}-${{ inputs.repository }}-${{ inputs.dependency }}
        restore-keys: ${{ env.KEY }}

    - name: Activate virtual environment
      shell: bash
      run: |
        echo "$(pwd)/.venv/bin" >> $GITHUB_PATH

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        python -m venv .venv

        if [ ${{ inputs.dependency }} ]; then
          requirement=${{inputs.dependency}}
        elif [ ${{ inputs.environment }} ]; then
          requirement=".[${{ inputs.environment }}]"
        else
          requirement="."
        fi
        if [ ${{ inputs.editable }} ]; then
          requirement="-e $requirement"
        fi
        pip install --upgrade pip
        pip install $requirement
