name: 'Run pre-commit hooks'
description: 'Run pre-commit hooks'

runs:
  using: 'composite'
  steps:
    - name: Setup environment
      uses: quintenroets/package-dev-tools/actions/setup/environment@dev
      with:
        environment: dev
        editable: true

    - name: Cache dependencies
      id: cache
      uses: actions/cache@v4
      env:
        KEY:
          pre-commit
          ${{ runner.os }}
          ${{ steps.determine-python-version.outputs.python_version }}
      with:
        path: |
          ~/.cache/pre-commit
          .mypy_cache
        key: ${{ env.KEY }}-${{ hashFiles('.pre-commit-config.yaml') }}
        restore-keys: ${{ env.KEY }}

    - name: Run hooks
      shell: bash
      run: pre-commit run --show-diff-on-failure --color=always --all-files
