name: Trigger template sync
description: Trigger template sync action in all repositories derived from template

inputs:
  token:
    description: 'Authentication token'

runs:
  using: composite
  steps:
  - name: Install dependencies
    run: pip install package-dev-tools
    shell: bash

  - name: Run trigger
    run: trigger-template-sync ${{ inputs.token }}
    shell: bash
