name: 'Extract Python versions'
description: 'Extract Python versions supported by the project'

outputs:
  versions:
    description: "The Python versions supported by the project"
    value: ${{ steps.extract-python-versions.outputs.versions }}

runs:
  using: 'composite'
  steps:
    - name: Setup environment
      uses: quintenroets/package-dev-tools/actions/setup/environment@main
      with:
        environment: dev

    - name: Extract Python version
      id: extract-python-versions
      shell: bash
      run: echo "versions=$(extract-supported-python-versions)" >> "$GITHUB_OUTPUT"
