name: Publish project
description: Publish project on PyPI

runs:
  using: composite
  steps:
    - name: Install dependencies
      shell: bash
      run: pip install build

    - name: Build
      run: python -m build
      shell: bash

    - name: Upload distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        skip-existing: true
