name: Build

on:
  push:

jobs:
  validate:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    name: Validate
    runs-on: {{ $matrix.os }}
    environment: release
    steps:
    - name: Validate
      uses: quintenroets/package-dev-tools/actions/validate@main
      env:
        TEMPLATE_SYNC_TRIGGER_TOKEN: ${{ secrets.TEMPLATE_SYNC_TRIGGER_TOKEN }}

  publish:
    name: Publish package
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: validate
    environment: release
    permissions:
      id-token: write  # Needed for PyPi publishing
      contents: write  # Needed for GitHub publishing
    steps:
      - name: Publish
        uses: quintenroets/package-dev-tools/actions/publish@main
