name: Build

on:
  push:

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    environment: release
    steps:
    - name: Validate
      uses: quintenroets/dev-tools/actions/validate@main

  publish:
    name: Publish package
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: validate
    environment: release
    permissions:
      id-token: write  # Needed for PyPi publishing
      contents: write  # Needed for GitHub publishing
    steps:
      - name: Publish
        uses: quintenroets/dev-tools/actions/publish@main
